import Link from "next/link";
import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Terms of Service — Just You",
  description: "The terms that govern using Just You.",
};

export default function TermsPage() {
  return (
    <div className="legal-page">
      <div className="legal-container">
        <Link href="/" className="legal-back">
          ← Back to Just You
        </Link>
        <h1 className="legal-title">Terms of Service</h1>
        <p className="legal-updated">Last updated October 8, 2026</p>
        <p className="legal-intro">
          These terms are between you and Just You, operated by Tea Ajazi, an individual. By using the app, you
          agree to them.
        </p>

        <section className="legal-section">
          <h2>What this is</h2>
          <p>
            Just You is a self-reflection tool. Replies are generated by AI, not written by a human, and nothing
            here substitutes for professional care. Just You is not therapy, not medical or psychological
            treatment, and not a crisis service.
          </p>
          <p>
            If you&apos;re in crisis or in danger, contact emergency services or a crisis line directly — in the
            US, that&apos;s 988. Please don&apos;t rely on this app in an emergency.
          </p>
        </section>

        <section className="legal-section">
          <h2>Eligibility</h2>
          <p>You must be 18 or older to use Just You.</p>
        </section>

        <section className="legal-section">
          <h2>Your account</h2>
          <p>
            There&apos;s no traditional account or password — a private, anonymous ID generated on your device
            stands in for one. If you lose access to that device without restoring your subscription by email
            first, we may not be able to recover your history.
          </p>
        </section>

        <section className="legal-section">
          <h2>Subscription</h2>
          <p>
            Just You offers an optional $9.99/month subscription for unlimited conversations (the free tier is
            limited). Subscribing is handled through Stripe Checkout; your card is billed by Stripe, not by us
            directly. You can cancel anytime through the subscription management portal in Settings —
            cancellation takes effect at the end of the current billing period, and we don&apos;t offer partial
            refunds for unused time.
          </p>
        </section>

        <section className="legal-section">
          <h2>Using Just You responsibly</h2>
          <p>
            Don&apos;t use the app to harm yourself or anyone else, to break the law, or to try to extract, abuse,
            or reverse-engineer the underlying system. We may suspend or end access for anyone who does.
          </p>
        </section>

        <section className="legal-section">
          <h2>No warranty</h2>
          <p>
            Just You is provided &ldquo;as is.&rdquo; We work to make it genuinely good, but we don&apos;t
            guarantee it will be error-free, uninterrupted, or right for your particular situation. Use your own
            judgment about anything it tells you — especially about real decisions with real consequences.
          </p>
        </section>

        <section className="legal-section">
          <h2>Limitation of liability</h2>
          <p>
            To the fullest extent the law allows, Just You and Tea Ajazi aren&apos;t liable for indirect,
            incidental, or consequential damages arising from your use of the app. Our total liability for any
            claim is limited to what you&apos;ve paid us in the past 12 months.
          </p>
        </section>

        <section className="legal-section">
          <h2>Changes</h2>
          <p>These terms may be updated as the app changes. If something material changes, we&apos;ll say so in the app.</p>
        </section>

        <section className="legal-section">
          <h2>Governing law</h2>
          <p>These terms are governed by the laws of the State of New York.</p>
        </section>

        <section className="legal-section">
          <h2>Contact</h2>
          <p>
            Questions about these terms: <a href="mailto:hello@justyou.fyi">hello@justyou.fyi</a>
          </p>
        </section>

        <div className="legal-cross-links">
          <Link href="/privacy">Privacy Policy</Link>
          <Link href="/">Back to Just You</Link>
        </div>
      </div>
    </div>
  );
}
